- id: terraform-format
  name: Terraform Format
  description: This hook validates and lints terraform code
  entry: hooks/terraform-format
  types: ['terraform']
  language: script
- id: kustomize-build
  name: Validate Kustomize Recipe
  description: This hook validates that a kustomization.yaml will yield a build
  entry: hooks/kustomize-build
  files: '^.ustomization(\.y.+)?'
  language: script
