#!/usr/bin/env bash
set -euo pipefail

for i in $*
do
    pushd `dirname $i`
    manifest=$(mktemp)
    kustomize build . -o $manifest
    # The intention was to run kubeval, but man it takes FOREVER on large yamls.  Disabling for now
    #kubeval --ignore-missing-schemas $manifest
    rm $manifest
    popd
done
