#!/usr/bin/env bash
set -euo pipefail

for i in $*
do
    pushd `dirname $i`
    tmpdir=$(mktemp -d)
    foundlist="$tmpdir/found"
    listedlist="$tmpdir/listed"
    find . -name \*.yaml| awk -F "/" '{print $NF}'|grep -vP '(^)?.ustomization(\.y.+)?'|sort > $foundlist
    cat `basename $i` | grep -vP '(^)?.ustomization(\.y.+)?'|grep -oFf $foundlist|sed 's,/(\+\\.y.ml),$1,g'|sort > $listedlist
    if [[ ! `diff -u $foundlist $listedlist >/dev/null` ]]
    then
        echo "We found $FOUND yaml files but kustomization only has $LISTED.  The following files aren't in the manifest:"
        diff -u $foundlist $listedlist
        exit 1
    fi
    popd
done
