#!/usr/bin/env bash
set -euo pipefail

for i in $*
do
    pushd `dirname $i`
    manifest=$(mktemp)
    kustomize build . -o $manifest
    kubeval --ignore-missing-schemas $manifest
    rm $manifest
    popd
done
